version: '3.3'
services:
  react-ui:
    container_name: react-ui
    build: .
    command: yarn start
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
